# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 13:00
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0033_auto_20170124_1300')
    ]

    state_operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('twitter_handle', models.CharField(blank=True, help_text='No @, No http://, just username', max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, help_text='For best display keep it square', null=True, upload_to='event/coaches/')),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'Coaches',
            },
            bases=(models.Model,),
        )
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
