# Generated by Django 3.2.19 on 2023-05-16 01:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coach", "0002_alter_coach_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="coach",
            unique_together={("name", "twitter_handle")},
        ),
    ]
