# Generated by Django 2.0 on 2017-12-17 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_auto_20180529_0016"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="application",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="applications.Application"),
        ),
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="applications.Question"),
        ),
        migrations.AlterField(
            model_name="email",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="author", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="form",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="applications.Form"),
        ),
        migrations.AlterField(
            model_name="score",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="scores", to="applications.Application"
            ),
        ),
        migrations.AlterField(
            model_name="score",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="scores", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
