# Generated by Django 1.11.7 on 2018-05-29 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0006_auto_20221231_1925"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="confirmation_mail",
            field=models.TextField(
                default="Hi there!\n\nThis is a confirmation of your application to <a href=\"http://djangogirls.org/{city}\">Django Girls {CITY}</a>. Yay! That's a huge step already, we're proud of you!\n\nMind that this is not a confirmation of participation in the event, but a confirmation that we received your application.\n\nYou'll receive an email from the team that organizes Django Girls {CITY} soon. You can always reach them by answering to this email or by writing to {your event mail}.\n\nPlease watch out for a confirmation email and add our email address to your address book, so that future emails do not go into spam. In the past, we have had many email invitations to the workshop go into spam and have had many applicants miss our invitation! We wouldn't want that to happen to you!\n\nFor your reference, we're attaching your answers below.\n\nHugs, cupcakes and high-fives!\nDjango Girls",
                help_text="Mail will be sent from your event mail.\nAlso the answers will be attached.",
            ),
        ),
    ]
