# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 12:44
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_auto_20151203_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.EventPage', unique=True),
        ),
    ]
