# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-17 16:46
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_auto_20160403_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.EventPage'),
        ),
    ]
