# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_auto_20160628_2154'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set([('form', 'email')]),
        ),
    ]
