# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-06 22:07
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0022_assign_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='page',
        ),
    ]
