# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-06 22:10
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0023_remove_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Event'),
        ),
    ]
