# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-31 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20151123_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='internal_comment',
            field=models.TextField(blank=True, default='', help_text="Write your comments here. They won't be sent to the company/organisation."),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='message_to_organisation',
            field=models.TextField(blank=True, default='', help_text='Write your message to the company/organisation here.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='state_province',
            field=models.CharField(blank=True, default='', help_text='If relevant, add the name of the state or province where the job is available.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetup',
            name='internal_comment',
            field=models.TextField(blank=True, default='', help_text="Write your comments here. They won't be sent to the company/organisation."),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetup',
            name='message_to_organisation',
            field=models.TextField(blank=True, default='', help_text='Write your message to the company/organisation here.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetup',
            name='organisation',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetup',
            name='recurrence',
            field=models.CharField(blank=True, default='', help_text='Provide details of recurrence if applicable.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetup',
            name='state_province',
            field=models.CharField(blank=True, default='', help_text='If relevant, add the name of the state or province where the meetup/event is happening.', max_length=255),
            preserve_default=False,
        ),
    ]
