# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-07 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20151123_1903'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='job',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='job',
            name='reviewer',
        ),
        migrations.AlterUniqueTogether(
            name='meetup',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='meetup',
            name='reviewer',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Meetup',
        ),
    ]
