# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('patreonmanager', '0001_initial'), ('patreonmanager', '0002_fundraisingstatus'), ('patreonmanager', '0003_auto_20160214_2008')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('twitter', models.CharField(blank=True, max_length=50, verbose_name='twitter')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('since', models.DateTimeField(blank=True, null=True, verbose_name='patron since')),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='last update')),
            ],
            options={
                'verbose_name': 'patron',
                'verbose_name_plural': 'patrons',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='month')),
                ('pledge', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='pledge')),
                ('status', models.CharField(choices=[('DECLINED', 'declined'), ('PROCESSED', 'processed')], default='PROCESSED', max_length=12, verbose_name='status')),
                ('completed', models.BooleanField(default=False, verbose_name='completed')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='patreonmanager.Patron', verbose_name='patron')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='value')),
            ],
            options={
                'ordering': ['value'],
                'verbose_name': 'reward',
                'verbose_name_plural': 'rewards',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='patreonmanager.Reward', verbose_name='reward'),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together=set([('patron', 'month')]),
        ),
        migrations.CreateModel(
            name='FundraisingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('number_of_patrons', models.IntegerField()),
                ('amount_raised', models.IntegerField()),
            ],
            options={
                'ordering': ('-date_updated',),
            },
        ),
    ]
