# Generated by Django 2.0 on 2017-12-17 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patreonmanager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="patron",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="patreonmanager.Patron",
                verbose_name="patron",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="reward",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="patreonmanager.Reward",
                verbose_name="reward",
            ),
        ),
    ]
