# Generated by Django 3.2.7 on 2021-09-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patreonmanager', '0003_auto_20210906_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraisingstatus',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patron',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
