# Generated by Django 3.2.7 on 2022-04-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20210906_0915"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_frozen",
            field=models.BooleanField(default=False, verbose_name="Event frozen because of some irregularities"),
        ),
    ]
