# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 08:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20160214_2008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'ordering': ('name',), 'verbose_name_plural': 'Coaches'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('pk',), 'verbose_name_plural': 'List of events'},
        ),
        migrations.AlterModelOptions(
            name='eventpage',
            options={'ordering': ('title',), 'verbose_name': 'Website'},
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2014, 7, 21, 8, 23, 26, 424244, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
