# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20160521_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='position',
        ),
    ]
