# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 17:01
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_sponsor_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmortem',
            options={'verbose_name': 'Statistics', 'verbose_name_plural': 'Statistics'},
        ),
        migrations.AlterField(
            model_name='event',
            name='photo_credit',
            field=models.CharField(blank=True, help_text="Only use pictures with a <a href='https://creativecommons.org/licenses/'>creative commons license</a>.", max_length=200, null=True),
        ),
    ]
