# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-31 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20160815_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='twitter_handle',
            field=models.CharField(blank=True, default='', help_text='No @, No http://, just username', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coach',
            name='url',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=75),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='latlng',
            field=models.CharField(blank=True, default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='photo_credit',
            field=models.CharField(blank=True, default='', help_text="Only use pictures with a <a href='https://creativecommons.org/licenses/'>creative commons license</a>.", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='photo_link',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='custom_css',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='description',
            field=models.TextField(blank=True, default='Django Girls is a one-day workshop about programming in Python and Django tailored for women.'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='main_color',
            field=models.CharField(blank=True, default='FF9400', help_text='Main color of the chapter in HEX', max_length=6),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='url',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postmortem',
            name='comments',
            field=models.TextField(blank=True, default='', verbose_name='Anything else you want to share with us?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postmortem',
            name='costs',
            field=models.TextField(blank=True, default='', help_text='We only collect this information for statistics and advice for future organizers.', verbose_name='What are the total costs of the event?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postmortem',
            name='discovery',
            field=models.TextField(blank=True, default='', verbose_name='What was the most important thing you discovered during the workshop?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postmortem',
            name='feedback',
            field=models.TextField(blank=True, default='', verbose_name='How we can make DjangoGirls better?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='url',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
