# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-06 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20160815_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_page_live',
            field=models.BooleanField(default=False, verbose_name='page published?'),
        ),
        migrations.AddField(
            model_name='event',
            name='page_custom_css',
            field=models.TextField(blank=True, verbose_name='custom CSS rules'),
        ),
        migrations.AddField(
            model_name='event',
            name='page_description',
            field=models.TextField(blank=True, default='Django Girls is a one-day workshop about programming in Python and Django tailored for women.', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='event',
            name='page_main_color',
            field=models.CharField(blank=True, default='FF9400', help_text='Main color of the chapter in HEX', max_length=6, verbose_name='main color'),
        ),
        migrations.AddField(
            model_name='event',
            name='page_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='event',
            name='page_url',
            field=models.CharField(blank=True, help_text='Will be used as part of the event URL (djangogirls.org/______/)', max_length=200, verbose_name='URL slug'),
        ),
        migrations.AlterField(
            model_name='event',
            name='email',
            field=models.EmailField(blank=True, max_length=75, null=True, verbose_name='event email'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='deleted?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_on_homepage',
            field=models.BooleanField(default=False, verbose_name='visible on homepage?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='latlng',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='latitude and longitude'),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo_credit',
            field=models.CharField(blank=True, help_text="Only use pictures with a <a href='https://creativecommons.org/licenses/'>Creative Commons license</a>.", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo_link',
            field=models.URLField(blank=True, null=True, verbose_name='photo URL'),
        ),
        migrations.AddField(
            model_name='eventpagecontent',
            name='event',
            field=models.ForeignKey(null=True, on_delete=models.deletion.CASCADE, related_name='content', to='core.Event'),
        ),
        migrations.AddField(
            model_name='eventpagemenu',
            name='event',
            field=models.ForeignKey(null=True, on_delete=models.deletion.CASCADE, related_name='menu', to='core.Event'),
        ),
    ]
