# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20160815_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'story', 'verbose_name_plural': 'stories'},
        ),
    ]
