# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-31 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20161031_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='photo',
            field=models.ImageField(blank=True, default='', help_text='For best display keep it square', upload_to='event/coaches/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, default='', help_text='The best would be 356 x 210px', upload_to='event/cities/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventpagecontent',
            name='background',
            field=models.ImageField(blank=True, default='', help_text='Optional background photo', upload_to='event/backgrounds/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(blank=True, default='', help_text='Make sure logo is not bigger than 200 pixels wide', upload_to='event/sponsors/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(default='', upload_to='stories/'),
            preserve_default=False,
        ),
    ]
