# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-06 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0023_remove_page'),
        ('core', '0023_auto_20170106_1931')
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventpagecontent',
            name='page',
        ),
        migrations.RemoveField(
            model_name='eventpagemenu',
            name='page',
        ),
        migrations.DeleteModel(
            name='EventPage',
        ),
    ]
