# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-06 22:10
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20170106_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpagecontent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='core.Event'),
        ),
        migrations.AlterField(
            model_name='eventpagemenu',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='core.Event'),
        ),
    ]
