# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 09:39
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20170106_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'story', 'verbose_name_plural': 'stories'},
        ),
    ]
