# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 13:29
from __future__ import unicode_literals

from django.db import migrations


def copy_stats_to_events(apps, schema_editor):
    Postmortem = apps.get_model('core', 'Postmortem')
    for postmortem in Postmortem.objects.select_related('event').all():
        event = postmortem.event
        event.applicants_count = postmortem.applicants_count
        event.attendees_count = postmortem.attendees_count
        event.save()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0026_auto_20170107_1326'),
    ]

    operations = [
        migrations.RunPython(copy_stats_to_events)
    ]
