# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_postmortem'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='offer_help_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='submit_information_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='thank_you_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
