# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_email_flags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
