# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 08:26
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20170113_0710'),
    ]

    database_operations = [
        migrations.AlterModelTable('Sponsor', 'sponsor_sponsor')
    ]

    state_operations = [
        migrations.DeleteModel('Sponsor'),

        migrations.RemoveField(
            model_name='eventpagecontent',
            name='sponsors',
        ),

        migrations.AddField(
            model_name='eventpagecontent',
            name='sponsors',
            field=models.ManyToManyField(to='sponsor.Sponsor', verbose_name='Sponsors'),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations
        ),
    ]
