# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20170124_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_on_homepage',
            field=models.BooleanField(default=True, verbose_name='visible on homepage?'),
        ),
    ]
