# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 13:38
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20170215_1404'),
    ]

    database_operations = [
        migrations.AlterModelTable('ContactEmail', 'contact_contactemail')
    ]

    state_operations = [
        migrations.DeleteModel('ContactEmail')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
