# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 11:53
from __future__ import unicode_literals

from django.db import migrations

def update_event_number_field(apps, schema_editor):
    Event = apps.get_model("core", "Event")
    for event in Event.objects.all():
        split_name = event.name.split('#')
        if len(split_name) <= 1:
            continue

        name = split_name[0]
        number = int(split_name[1])
        if number <= 1:
            continue

        event.name = name
        event.number = number
        event.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_event_number'),
    ]

    operations = [
        migrations.RunPython(
            update_event_number_field,
            migrations.RunPython.noop
        )
    ]
