# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 18:23
import core.validators
from django.db import migrations
import django_date_extensions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20170221_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=django_date_extensions.fields.ApproximateDateField(blank=True, default='', validators=[core.validators.validate_approximatedate]),
            preserve_default=False,
        ),
    ]
