# Generated by Django 1.11.5 on 2017-12-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Make sure logo is not bigger than 200 pixels wide",
                        null=True,
                        upload_to="event/sponsors/",
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
