# Generated by Django 1.11.7 on 2018-06-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donor",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("amount", models.FloatField()),
                ("visible", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("amount",),
            },
        ),
    ]
