# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-03 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0003_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='picture',
            field=models.FileField(upload_to=''),
        ),
    ]
