# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-03 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0004_auto_20180503_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='quote',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
