# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-03 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0005_auto_20180503_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
