#!/usr/bin/env bash

# Get secret token values from https://opbeat.com/django-girls/djangogirlsorg/releases/setup/instructions/
function notify_opbeat_release {
    echo "Uploading release to opbeat..."
    curl https://intake.opbeat.com/api/v1/organizations/<snip>/apps/<snip>/releases/ \
        -H "Authorization: Bearer <snip>" \
        -d rev=`git log -n 1 --pretty=format:%H` \
        -d branch=`git rev-parse --abbrev-ref HEAD` \
        -d status=completed
}

notify_opbeat_release
