# Generated by Django 2.0 on 2017-12-17 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organize", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventapplication",
            name="previous_event",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.Event"
            ),
        ),
    ]
