# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventapplication',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_review', 'In review'), ('on_hold', 'On hold'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='new', max_length=10),
        ),
        migrations.AddField(
            model_name='eventapplication',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
