# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0001_squashed_0004_remove_eventapplication_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventapplication',
            name='about_you',
            field=models.TextField(verbose_name='About organizer'),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='coaches',
            field=models.TextField(verbose_name='Information about your potential coaches'),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='experience',
            field=models.TextField(verbose_name='Experience with organizing other events'),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='involvement',
            field=models.CharField(max_length=100, verbose_name='Involvement in Django Girls'),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='sponsorship',
            field=models.TextField(verbose_name='Information about your potential sponsorship'),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_review', 'In review'), ('on_hold', 'On hold'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('deployed', 'Deployed')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='venue',
            field=models.TextField(verbose_name='Information about your potential venue'),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='why',
            field=models.TextField(verbose_name='Motivations to organize'),
        ),
    ]
