# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 18:08
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0003_auto_20170115_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventapplication',
            name='website_slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='city', unique=True),
        ),
    ]
