# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 18:51
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0003_auto_20170107_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventapplication',
            name='rejection_reason',
        ),
    ]
