# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 18:10
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0004_auto_20170116_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coorganizer',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='main_organizer_last_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
