# Generated by Django 1.11.5 on 2017-12-16 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contact", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactemail",
            name="event",
            field=models.ForeignKey(
                blank=True,
                help_text="required for contacting a chapter",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.Event",
            ),
        ),
    ]
