# Generated by Django 2.0 on 2017-12-17 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_contactemail_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactemail",
            name="event",
            field=models.ForeignKey(
                blank=True,
                help_text="required for contacting a chapter",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.Event",
            ),
        ),
    ]
