name: 🐛 Bug Report
description: Create a bug report to help us improve Django Girls.
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below to help us reproduce and fix the bug. Your feedback is invaluable to us.

  - type: textarea
    id: description
    attributes:
      label: Brief description of the issue
      description: A clear and concise description of what the bug is.
      placeholder: Please provide a detailed description of the bug, and feel free to include screenshots if available. Thank you! ✨
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect to happen?
      description: Tell us what you expected to happen.
      placeholder: Could you please describe what you expected to happen? Thank you! ✨
    validations:
      required: true