# Generated by Django 3.2.16 on 2023-01-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlobalPartner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("company_name", models.CharField(max_length=100)),
                ("contact_person", models.CharField(max_length=100)),
                ("contact_email", models.EmailField(max_length=100)),
                ("prospective_sponsor", models.BooleanField(default=False)),
                ("patreon_sponsor", models.BooleanField(default=False)),
                (
                    "patreon_sponsor_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("$100/month", "$100/month"),
                            ("$250/month", "$250/month"),
                            ("$500/month", "$500/month"),
                            ("$1,000/month", "$1,000/month"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "sponsor_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Bronze ($500)", "Bronze ($500)"),
                            ("Silver ($1000)", "Silver ($1000)"),
                            ("Gold ($2,500)", "Gold ($2,500)"),
                            ("Platinum ($5,000)", "Platinum ($5,000)"),
                            ("Diamond ($10,000", "Diamond ($10,000"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("date_joined", models.DateField(blank=True, null=True)),
                ("contacted", models.BooleanField(default=False)),
                ("date_contacted", models.DateField(blank=True, null=True)),
                ("next_renewal_date", models.DateField(blank=True, null=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="uploads")),
                ("is_displayed", models.BooleanField(default=False)),
                ("website_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
