# Generated by Django 3.2.16 on 2023-02-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("globalpartners", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="globalpartner",
            name="patreon_sponsor_level",
        ),
        migrations.RemoveField(
            model_name="globalpartner",
            name="sponsor_level",
        ),
        migrations.AddField(
            model_name="globalpartner",
            name="patreon_level_per_month",
            field=models.IntegerField(
                blank=True, choices=[(100, 100), (250, 250), (500, 500), (1000, 1000)], null=True
            ),
        ),
        migrations.AddField(
            model_name="globalpartner",
            name="sponsor_level_annual",
            field=models.IntegerField(
                blank=True, choices=[(500, 500), (1000, 1000), (2500, 2500), (5000, 5000), (10000, 10000)], null=True
            ),
        ),
        migrations.AddField(
            model_name="globalpartner",
            name="style",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
