# Generated by Django 3.2.16 on 2023-02-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("globalpartners", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalpartner",
            name="sponsor_level_annual",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (500, "Bronze ($500)"),
                    (1000, "Silver ($1000)"),
                    (2500, "Gold ($2,500)"),
                    (5000, "Platinum ($5,000)"),
                    (10000, "Diamond ($10,000)"),
                ],
                null=True,
            ),
        ),
    ]
