# Generated by Django 3.2.18 on 2023-03-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("globalpartners", "0002_alter_globalpartner_sponsor_level_annual"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalpartner",
            name="description",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
