# Generated by Django 3.2.20 on 2024-02-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("globalpartners", "0003_globalpartner_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalpartner",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="globalpartner",
            name="promotional_materials_requested",
            field=models.BooleanField(default=False),
        ),
    ]
