# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('story', '0001_initial'), ('story', '0002_auto_20170115_1619')]

    initial = True

    dependencies = [
        ('core', '0031_auto_20170113_0710'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Story',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=100)),
                        ('content', models.TextField(null=True)),
                        ('post_url', models.URLField()),
                        ('image', models.ImageField(null=True, upload_to='stories/')),
                        ('created', models.DateField(auto_now_add=True)),
                        ('is_story', models.BooleanField(default=True)),
                    ],
                    options={
                        'verbose_name': 'story',
                        'verbose_name_plural': 'stories',
                    },
                ),
            ],
        ),
        migrations.AlterField(
            model_name='story',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
