# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 07:12
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0031_auto_20170113_0710')
    ]

    state_operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField(null=True)),
                ('post_url', models.URLField()),
                ('image', models.ImageField(null=True, upload_to='stories/')),
                ('created', models.DateField(auto_now_add=True)),
                ('is_story', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'story',
                'verbose_name_plural': 'stories',
            },
            bases=(models.Model,),
        )
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
