# Generated by Django 3.2.16 on 2022-12-29 16:32

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField()),
                ("logo", models.ImageField(upload_to="")),
            ],
            options={
                "verbose_name_plural": "companies",
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("summary", models.TextField(max_length=300)),
                ("description", tinymce.models.HTMLField()),
                ("open", models.BooleanField(default=True)),
                ("remuneration", models.CharField(blank=True, max_length=50, null=True)),
                ("apply", models.URLField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="jobboard.company")),
            ],
        ),
    ]
