# Generated by Django 3.2.16 on 2022-12-20 22:45

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('remote', models.BooleanField(default=False)),
                ('description', tinymce.models.HTMLField()),
                ('open', models.BooleanField(default=True)),
                ('apply', models.URLField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobboard.company')),
            ],
        ),
    ]
