# Generated by Django 3.2.16 on 2023-02-02 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("globalpartners", "0001_initial"),
        ("jobboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="company",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="globalpartners.globalpartner"),
        ),
        migrations.DeleteModel(
            name="Company",
        ),
    ]
