# Generated by Django 3.2.16 on 2022-12-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='remuneration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
