# Generated by Django 3.2.16 on 2022-12-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0003_job_remuneration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='remote',
        ),
        migrations.AddField(
            model_name='job',
            name='summary',
            field=models.TextField(default='Test text', max_length=200),
            preserve_default=False,
        ),
    ]
