# Generated by Django 3.2.20 on 2024-11-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecharge',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stripecharge',
            name='charge_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
