# Generated by Django 3.2.20 on 2024-11-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payments', '0002_auto_20241106_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecharge',
            name='charge_id',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
